### PR TITLE
struct

### PR DESCRIPTION
**Pull request by gertcuykens**

### CODE REVIEW

**Comment by colindev** [comment]
Thx for your PR and issue
this PR, I need more time to review...

**Review by colindev — APPROVED** [review]
this look nice

**Comment by colindev** [comment]
I found time format on local machine and Travis CI has different display
but i don't exactly sure why it happen
https://play.golang.org/p/a0-hk0JFSE

maybe it's because default timezone in different machine is not the same?

**Comment by gertcuykens** [comment]
Probably

**Pull request merged**
